import type { Transport } from "./transport";
import type { SaltResponse, SessionTokens } from "./types";

/**
 * Register, sign in, and end a session.
 *
 * A port of the auth half of `crates/client/src/session.rs`. The password
 * itself never reaches this file and never reaches the server: the caller
 * derives a verifier from the password and the account's salt, and what
 * travels is the verifier. A server that is compromised at the moment somebody
 * signs in sees that verifier — better than seeing a password, worse than a
 * real PAKE, and written down in `docs/THREAT-MODEL.md` §5 rather than
 * implied to be more.
 */

/**
 * The per-account salt, fetched before the verifier is derived.
 *
 * **An unknown handle still gets a salt**, and that is the point: answering
 * "no such account" here would turn this route into a way to test whether
 * somebody has one. The server mints a stable decoy from the handle, so the
 * two cases are indistinguishable from outside.
 */
export function salt(transport: Transport, handle: string): Promise<SaltResponse> {
  return transport.post<SaltResponse>("/v1/auth/salt", { handle });
}

export interface RegisterInput {
  handle: string;
  displayName: string;
  /** Hex. Generated by the caller, never by the server. */
  pwSalt: string;
  /** Hex. Argon2id over the password and the salt above. */
  pwVerifier: string;
  /** Hex. The long-term identity public key. */
  identityPubkey: string;
}

export async function register(
  transport: Transport,
  input: RegisterInput,
): Promise<SessionTokens> {
  const tokens = await transport.post<SessionTokens>("/v1/auth/register", {
    handle: input.handle,
    display_name: input.displayName,
    pw_salt: input.pwSalt,
    pw_verifier: input.pwVerifier,
    identity_pubkey: input.identityPubkey,
  });
  return tokens;
}

export async function login(
  transport: Transport,
  handle: string,
  pwVerifier: string,
  identityPubkey: string,
): Promise<SessionTokens> {
  const tokens = await transport.post<SessionTokens>("/v1/auth/login", {
    handle,
    pw_verifier: pwVerifier,
    identity_pubkey: identityPubkey,
  });
  return tokens;
}

/**
 * End this session on the server, then locally.
 *
 * Local first would leave a live refresh token on the server that nothing can
 * ever spend or revoke; server first means a failure leaves the session usable
 * rather than stranded, which is the better way round to fail.
 */
export async function logout(transport: Transport, refreshToken: string): Promise<void> {
  try {
    await transport.postAuth<void>("/v1/auth/logout", { refresh_token: refreshToken });
  } finally {
    transport.clear();
  }
}
